Add warnings for errors

diff --git a/.github/workflows/lint_mypy_pylint.yml b/.github/workflows/lint_mypy_pylint.yml
--- a/.github/workflows/lint_mypy_pylint.yml
+++ b/.github/workflows/lint_mypy_pylint.yml
@@ -34,6 +34,14 @@ jobs:
         run: |
           mypy distributedinference/ > mypy_pyright_outputs/mypy_output.txt || true
         continue-on-error: true
+      - name: Count mypy errors
+        id: mypy-count
+        run: |
+          error_count=$(grep -oP "\d+ errors" mypy_output.txt | sed 's/ errors//g' || echo 0)
+          echo "Mypy error count: $error_count"
+          if [[ "$error_count" -gt 0 ]]; then
+            echo "::warning::Found $error_count mypy errors."
+          fi
       - name: Print mypy output
         run: |
           echo "=== mypy output ==="
@@ -42,6 +50,14 @@ jobs:
         run: |
           pyright distributedinference/ > mypy_pyright_outputs/pyright_output.txt || true
         continue-on-error: true
+      - name: Count pyright errors
+        id: pyright-count
+        run: |
+          error_count=$(grep -oP "\d+ errors" pyright_output.txt | sed 's/ errors//g' || echo 0)
+          echo "pyright error count: $error_count"
+          if [[ "$error_count" -gt 0 ]]; then
+            echo "::warning::Found $error_count pyright errors."
+          fi
       - name: Print pyright output
         run: |
           echo "=== pyright output ==="
